### ISSUE TITLE
Gestion des noeuds du cluster

### ISSUE THREAD

**Issue by Johayon** [AndreiArion/bigdata-project-2014#11]
L'énoncé demande un cluster de 5 noeuds pour les données dans les 5 plus grandes villes du Japon, faut-il gère la possibilité que plus de 2 peuvent tomber avec un tremblement de terre. Tokyo, Yokohama, Nagoya et Osaka  peuvent se retrouver dans la zone d'un rayon de 500km dont l'épicentre est dans le large, dans ce cas extreme 4 des noeuds tombent, il n'en reste qu'un seul. 
Sommes nous obligés de garder ces 5 villes ? Doit-on rajouter des noeuds supplémentaires pour le cluster de données ?

**Comment by AndreiArion** [comment]
Il faut prévoir uniquement le cas d'un nœud qui tombe. La taille de votre cluster c'est juste une indication, il faut juste prévoir le cas d'un nœud de données qui tombe. Voir aussi https://github.com/AndreiArion/bigdata-project-2014/issues/6 .
