### ISSUE TITLE
Gestion de Spark

### ISSUE THREAD

**Issue by Johayon** [AndreiArion/bigdata-project-2014#12]
Pour l'utilisation de Spark, qui a besoin d'un master, peut-on simuler que le master n'est pas au japon ?
Sinon comment gérer le besoin d'un noeud master dans le stack ?

**Comment by AndreiArion** [comment]
Vous n'etes pas obligés de gérer la redondance du noeud qui lance la simulation. Voir https://github.com/AndreiArion/bigdata-project-2014/issues/6 pour plus de détails.
