### ISSUE TITLE
Jeu de données projet Big Data

### ISSUE THREAD

**Issue by christianBGD** [AndreiArion/bigdata-project-2014#4]
Bonjour,

j'aimerais avoir accès à des jeux de données plus importants (celui de 1m ne contient pas de doublon de n° de tél.)

Merci de votre aide.

Christian

**Comment by charlesherriau** [comment]
Bonjour Christian,

- Tu peux télécharger les fichiers depuis AWS :
s3n://bigdata-paristech/projet2014/data/data_1GB.csv
s3n://bigdata-paristech/projet2014/data/data_10GB.csv
Ils sont disponible uniquement depuis AWS

- Tu peux trouver le fichier de 1Go en téléchargement normal ici : https://lesfurets-my.sharepoint.com/personal/charles_herriau_lesfurets_com/_layouts/15/guestaccess.aspx?guestaccesstoken=1dbWX7RGFupn7x%2fGtICqEER1UICbwPJmV9WYZY2xBqg%3d&docid=0018df95c19754b8593ae10b522a9a27d
