### ISSUE TITLE
Chargement CSV avant démonstration 

### ISSUE THREAD

**Issue by florianriche** [AndreiArion/bigdata-project-2014#5]
Bonjour

Devons-nous considérer que l'insertion des données des fichiers CSV  fait partie de la "démo" et que c'est donc à optimiser ou alors est-ce une étape préliminaire à avoir fait avant la démonstration?

Merci pour votre réponse!

**Comment by AndreiArion** [comment]
Bonjour Florian,

*Les données doivent être chargées avant la soutenance*.

On a mis dans le paragraphe 4(4. IV. Organisation) un warning:

*"Lors de cette soutenance, les données devront être préalablement
chargées dans votre cluster. La date, l’heure et les coordonnées du
tremblement de terre vous seront révélées au début de la démo
"*

Est-ce que tu pense qu'on doit reformuler ce paragraphe pour qu'il soit un peu plus claire?

Merci,

**Comment by florianriche** [comment]
Merci pour cette réponse, j'avais le doute effectivement. Après relecture, c'était assez clair et je pense que les gens auront vu l'issue ouverte et auront eu confirmation.
