### ISSUE TITLE
Distribution du/des serveur(s) applicatif(s)

### ISSUE THREAD

**Issue by anthonyray** [AndreiArion/bigdata-project-2014#6]
Bonjour,

L'énoncé indique que nous devons monter un cluster de données constitué de 5 noeuds. 
La logique applicative doit-elle être elle aussi distribuée sur ce même cluster de 5 noeuds ? Ou pouvons-nous imaginer qu'il existe un "centre de contrôle" à l'abri des séisme et qui centralise la logique applicative (i.e un serveur EC2 à part qu'on ne va pas shutdown) ?

Merci !

**Comment by AndreiArion** [comment]
Le nombre de noeuds de votre clusteur est libre, vous pouvez rajouter plus de noeuds ou enlever. Il faut juste avoir une mapping entre vos noeuds et villes pour pouvoir couper le(s) noeud(s) affectées.

Vous pouvez utiliser une machine externe (EC2 ou votre laptop...) ou l'un des noeuds du clusteur (hormis le nœud HS) pour piloter la simulation.

**Comment by anthonyray** [comment]
Merci !
