### ISSUE TITLE
Format du timestamp

### ISSUE THREAD

**Issue by dluzenst** [AndreiArion/bigdata-project-2014#7]
La commande COPY ne semble pas importer correctement les données timestamp. Le problème se pose au niveau des millisecondes:

cqlsh> CREATE TABLE ks.sample3 ( time timestamp, station varchar, lat double, lon double, phone varchar, PRIMARY KEY (time, station, lat, lon));
cqlsh> COPY ks.sample3 FROM 'sample.csv' WITH DELIMITER=';';

code=2200 [Invalid query] message="unable to coerce '2015-01-18 09:19:16,888' to a  formatted date (long)"
Aborting import at record #1. Previously-inserted values still present.
0 rows imported in 0.018 seconds.

Si j'enlève les millisecondes manuellement du .csv le COPY se fait correctement.

Comment faire en sorte que COPY accepte les millisecondes?
J'ai essayé sans succès de rajouter une ligne time_format à mon cqlshrc: 
time_format = '%Y-%m-%d %H:%M:%f'
Y-a-t'il une erreur dans ce format?
comment faire?

**Comment by AndreiArion** [comment]
Le time_format du .cqlshrc n'est utilise que lorsq'on veux afficher dans cqlsh des dates dans un format particulier. 

Pour le problème d'import, les dates du fichier sont en format  ISO-8601 mais Cassandra semble supporter uniquement une partie du ce standard RFC3339 dans lequel on doit avoir des . pour les fractions de seconde.

Du coup il faut transformer les dates avant d'appeler le COPY:
- soit tu remplace les , par des . =>  '2015-01-18 09:19:16.888' ça devrait  passer
- soit tu coupe les fractions de seconde (de toute maniere il n'ont pas d'interet pour le projet) => ''2015-01-18 09:19:16' ca doit passer egalement

**Comment by dluzenst** [comment]
Merci! J'ai résolu le problème, comme suggéré, par un pré-traitement sous python.
